### ISSUE TITLE
Only transmission

### ISSUE THREAD

**Issue by neckaros** [Modjor/transblocker#3]
Hello,
With this script only transmission traffic use VPN?

**Comment by fn002449** [comment]
This script sets up the firewall rules and makes sure tranmission is using VPN.

**Comment by Modjor** [comment]
Hello,

No, transblocker does NOT route only transmission traffic. It only make sure that transmission is only using your VPN connection - and do not allow Transmission traffic if there is no VPN available.


If you want to restrict the traffic of any app hosted on your NAS, you should probably setup a firewall rule on your router, and only allow traffic coming from your NAS going to your VPN provider. This way if the VPN is down, nothing will go out of your network from your NAS.

In that situation, you most likely would not need transblocker.
