### ISSUE TITLE
More than one ovpn connections failure?

### ISSUE THREAD

**Issue by dorianps** [Modjor/Transblocker#5]
Thank you for writing this code. I haven't tried it yet because I have a long list of ovpn connections on the NAS. It was already difficult to put them in because of compatibility problems with VPN unlimited.

Is there a way you can update this script to use a specific connection, instead of failing when it sees many ovpn options?

**Comment by Modjor** [comment]
Sorry mate, no plan to update the script (I don't have the need for this feature nor the time to code it).
This being said, I never tried with multiple ovpn connection, so I'm not entirely sure of what will happen...

My guess is that the script will try to connect the first ovpn of the list.  But no guarantee.
